{
systems:
{
  fiware: { type: fiware, host: "172.18.0.3", port: 1026 },
  ws_server_for_fiware: { type: websocket_server, security: none, host: localhost, port: 12345, types-from : ros2,
      authentication:
      {
        policies: [{ secret: is-web-api, algo: HS256 }]
      }
  }
},
routes:
{
  websocket_to_fiware: { from: ws_server_for_fiware, to: fiware },
  fiware_to_websocket: { from: fiware, to: ws_server_for_fiware }
}
}
